name: Cache Cargo Packages
description: "Cache Cargo Packages compatible with Namespace Lab's runners"
inputs:
  namespacelabs:
    default: 'true'
    description: "Using Namespace Lab's runners"
branding:
  color: blue
  icon: archive
runs:
  using: 'composite'
  steps:
    # NAMESPACE LAB VERSION
    - uses: namespacelabs/nscloud-cache-action@v1
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
      if: inputs.namespacelabs == 'true'

    # NATIVE VERSION
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
      if: inputs.namespacelabs == 'false'
